routes/web.php
<?php
use App\Models\faq\QuestionCategory;
use Illuminate\Http\Request;

// auth routes
Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('login', 'Auth\LoginController@login')->name('login');
Route::post('logout', 'Auth\LoginController@logout')->name('logout');

Route::get('register', 'Auth\RegisterController@showRegistrationForm')->name('register');
Route::post('register', 'Auth\RegisterController@register')->name('register');

Route::group(array('as' => 'password.'), function() {
    Route::get('password/reset/{token?}/{email?}', 'Auth\ResetPasswordController@showResetForm')->name('reset');
    Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('email');
    Route::post('password/reset', 'Auth\ResetPasswordController@reset')->name('reset');
});

Route::get('register/confirm/{token}', 'Auth\RegisterController@confirmEmail');
Route::get('auth/{provider}', 'Auth\LoginController@redirectToProvider');
Route::get('auth/{provider}/callback', 'Auth\LoginController@handleProviderCallback');
Route::get('notActive', 'Auth\UserController@active')->name('notActive');
// auth routes end

Route::get('/', function () {
    return redirect()->route('login');
});

Route::group(['middleware' => ['checkActive']], function () {
    Route::resource('profile', 'ProfileController');
    Route::post('profile/pass/{profile}', 'ProfileController@passwords')->name('profile.pass');
    Route::post('profile/email/{profile}', 'ProfileController@email')->name('profile.email');

    Route::resource('profile', 'ProfileController');
    Route::post('profile/pass/{profile}', 'ProfileController@passwords')->name('profile.pass');

    //products
    Route::post('/product/form/category-dependent-block', 'Product\ProductFormController@categoryDependentBlock');
    Route::post('/product/form/second-step', 'Product\ProductFormController@secondStep');
    Route::post('/product/form/institution', 'Product\ProductFormController@institution');

    //phone
    Route::get('phone/form', 'ProfileController@showPhoneForm')->name('phone.form');
    Route::post('phone/save', 'ProfileController@savePhone')->name('phone.save');

    Route::group(['middleware' => ['checkRoute']], function () {
        Route::group(['middleware' => 'role:user'], function () {
            Route::get('/dashboard', function () {
                return view('user_dashboard', [
                    'nFair' => Fair::getNearestFair(),
                    'cFair' => Fair::getCurrentFair(),
                    'lFair' => Fair::getLatestFair(),
                ]);
            })->name('dashboard');

            // products
            Route::post('/products/destroy', 'Product\ProductController@destroy')->name('products.destroy');
            Route::patch('/users/{user}/products/{product}', 'Product\ProductController@update')->name('products.update');
            Route::resource('products', 'Product\ProductController', ['except' => ['destroy', 'update']]);
            Route::get('/user/{user}/pricelist/download', 'Product\ProductController@downloadPriceList')->name('pricelist.download');
            Route::get('/{user}/products/{product}/duplicate', 'Product\ProductController@duplicate')->name('products.duplicate');

            // deliveries
            Route::post('/deliveries/destroy', 'DeliveryController@destroy')->name('deliveries.destroy');
            Route::patch('/users/{user}/deliveries/{delivery}', 'DeliveryController@update')->name('deliveries.update');
            Route::post('/deliveries/create', 'DeliveryController@create')->name('deliveries.create');
            Route::resource('deliveries', 'DeliveryController', ['except' => ['show', 'destroy', 'update']]);

            //withdraw money
            Route::get('/money/withdraw', 'MoneyController@withdraw')->name('money.withdraw');
            Route::get('/money/index', 'MoneyController@index')->name('money.index');

            //FAQ
            Route::resource('faq', 'FAQController', ['only' => ['index']]);
        });

        Route::group(['middleware' => 'role:admin', 'prefix' => 'admin', 'namespace' => 'Admin'], function () {
            Route::get('/dashboard', function () {
                return view('admin_dashboard', ['fair' => Fair::getNearestFair()]);
            })->name('admin.dashboard');

            //settings
            Route::get('settings/revenue_percent/update', 'SettingController@globalUpdateRevenuePercent')->name('settings.revenuePercent.update');
            Route::resource('settings', 'SettingController', ['only' => ['index', 'update']]);

            //deliveries list of the user
            Route::post('/users/{user}/deliveries/destroy', 'Users\DeliveryController@destroy')->name('users.deliveries.destroy');
            Route::get('users/{userId}/deliveries/{deliveryId}/confirm', 'Users\DeliveryController@confirm')
                ->name('users.deliveries.confirm');
            Route::any('/users/{user}/deliveries/create', 'Users\DeliveryController@create')->name('users.deliveries.create');
            Route::resource('users.deliveries', 'Users\DeliveryController', ['only' => ['index', 'edit', 'update', 'store']]);
            //full deliveries list
            Route::patch('/{user}/deliveries/{delivery}', 'DeliveryController@update')->name('admin.deliveries.update');
            Route::post('/deliveries/destroy', 'DeliveryController@destroy')->name('admin.deliveries.destroy');
            Route::resource('deliveries', 'DeliveryController', [
                'only' => ['index', 'edit'],
                'names' => [
                    'index'  => 'admin.deliveries.index',
                    'edit'   => 'admin.deliveries.edit'
                ]
            ]);
            Route::any('deliveries/filter', 'DeliveryController@filter')->name('admin.deliveries.filter');

            //products of the user
            Route::get('/users/{id}/products/download', 'Users\ProductController@download')->name('users.products.download');
            Route::post('/users/{userId}/products/destroy', 'Users\ProductController@destroy')->name('users.products.destroy');
            Route::any('/users/{user}/products/create', 'Users\ProductController@create')->name('users.products.create');
            Route::resource('users.products', 'Users\ProductController', ['except' => ['destroy', 'create']]);
            Route::get('/users/{user}/pricelist/download', 'Users\ProductController@downloadPriceList')->name('users.pricelist.download');
            Route::get('/users/{user}/products/{product}/duplicate', 'Users\ProductController@duplicate')->name('users.products.duplicate');
            //full products list
            Route::get('/products/download', 'ProductController@download')->name('products.download');
            Route::post('products/destroy', 'ProductController@destroy')->name('admin.products.destroy');
            Route::patch('/user/{user}/products/{product}', 'ProductController@update')->name('admin.products.update');
            Route::resource('products', 'ProductController', [
                'only' => ['index', 'show', 'edit'],
                'names' => [
                    'index'  => 'admin.products.index',
                    'show'   => 'admin.products.show',
                    'edit'   => 'admin.products.edit'
                ]
            ]);
            Route::get('products/filter/categories/{category}', 'ProductController@filterByCategory')->name('admin.products.filter.category');
            Route::any('products/filter/statuses', 'ProductController@filterByStatus')->name('admin.products.filter.status');
            Route::any('products/confirm/transfer', 'ProductController@confirm')->name('admin.products.confirm');
            Route::get('/user/{user}/products/{product}/duplicate', 'ProductController@duplicate')->name('admin.products.duplicate');

            //fairs
            Route::resource('fairs', 'FairController', ['only' => ['index', 'edit', 'update']]);

            //users
            Route::get('users/download', 'UserController@download')->name('users.download');
            Route::any('users/filter', 'UserController@filter')->name('users.filter');
            Route::get('users/{user}/money/withdraw/confirm', 'UserController@confirmWithdrawMoney')->name('users.confirmWithdrawMoney');
            Route::resource('users', 'UserController', ['only' => ['index', 'show', 'destroy']]);

            //FAQ
            Route::group(['prefix' => 'faq'], function () {
                Route::post('/questions/categories/select', function (Request $request) {
                    return view('admin.faq.question_category._select', [
                        'selected' => $request->category_id, 'categories' => QuestionCategory::all()
                    ])->render();
                });
                Route::resource('questions', 'faq\QuestionController', [
                    'except' => ['create', 'edit', 'show']
                ]);

                Route::group(['prefix' => 'questions'], function () {
                    Route::resource('categories', 'faq\QuestionCategoryController', [
                        'except' => ['create', 'edit', 'show'],
                        'names' => ['index' => 'questions.categories.index']
                    ]);
                });
            });
        });
    });
});

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Helpers\CommonHelper;
use App\Models\User;
use Carbon\Carbon;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $users = User::with(['products'])->get();
        if (count($users) > 0) {
            $this->setParams($users);
        }

        return view('admin.user.index', ['users' => $users]);
    }

    /**
     * Show user page.
     *
     * @param $id
     * @return $this|\Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function show($id)
    {
        $user = User::find($id);
        if (is_null($user))
            return redirect()->back()->withErrors(trans('messages.userDoesNotExistError', ['id' => $id]));

        return view('admin.user.show', ['user' => $user]);
    }

    /**
     * Set params for users
     *
     * @param $users
     */
    protected function setParams($users)
    {
        foreach ($users as $user) {
            $user->countProducts = $user->products->count();
            $user->countDonateProducts = $user->getNumberOfDonatedProducts();
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $user = User::find($id);
        if (is_null($user))
            return redirect()->back()->withErrors(trans('messages.userDoesNotExistError', ['id' => $id]));

        $user->products()->delete();
        $user->deliveries()->delete();
        $result = $user->delete();

        if (!$result)
            flash(trans('messages.errDeletedUser'), 'error');
        else
            flash(trans('messages.deletedUser'))->success();

        return redirect()->back();
    }

    /**
     * @param Request $request
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function filter(Request $request)
    {
        $query = User::query();

        //filter by name
        if ($request->name)
            $query->where('first_name', 'like', '%' . $request->name . '%');

        //filter by age
        if (!is_null($request->age_from)) {
            $fromBirthday = Carbon::now()->subYears((int) $request->age_from)->format('Y-m-d');
            $query->where('birthday', '<=', $fromBirthday);
        }
        if (!is_null($request->age_to)) {
            $toBirthday = Carbon::now()->subYears((int) $request->age_to)->format('Y-m-d');
            $query->where('birthday','>=', $toBirthday);
        }

        $users = $query->get();
        if (count($users) > 0) {
            foreach ($users as $userKey => $user) {
                $productCount = $user->productsCount();
                $donatedProductCount = $user->getNumberOfDonatedProducts();
                $revenue = $user->getTotalRevenue();
                $isValidUser = true;

                //filter by products
                if (!is_null($request->products_from)) {
                    if ($productCount < (int)$request->products_from)
                        $isValidUser = false;
                }
                if (!is_null($request->products_to)) {
                    if ($productCount > (int)$request->products_to)
                        $isValidUser = false;
                }

                //filter by donated products
                if (!is_null($request->donate_from)) {
                    if ($donatedProductCount < (int)$request->donate_from)
                        $isValidUser = false;
                }
                if (!is_null($request->donate_to)) {
                    if ($donatedProductCount > (int)$request->donate_to)
                        $isValidUser = false;
                }

                //filter by revenue
                if (!is_null($request->sum_from)) {
                    if ($revenue < (int)$request->sum_from)
                        $isValidUser = false;
                }
                if (!is_null($request->sum_to)) {
                    if ($revenue > (int)$request->sum_to)
                        $isValidUser = false;
                }

                //unset invalid user
                if (!$isValidUser)
                    unset($users[$userKey]);
            }
        }

        if (count($users) > 0) {
            $this->setParams($users);
        }

        if (!empty($request->all()))
            flash(trans('messages.filteredUser'))->success();

        return view('admin.user.index', ['users' => $users, 'filter' => $request->all()]);
    }

    /**
     * Download excel file with user data.
     *
     * @return \Illuminate\Http\RedirectResponse
     */
    public function download()
    {
        $fileName = 'users_' . Carbon::today()->format('d_m_y') . '_' . time();
        $thData = [
            trans('auth.regFstName'),
            trans('auth.regLstName'),
            trans('auth.regEmail'),
            trans('auth.regPhone'),
            trans('basic.sum') . ', ' . trans('basic.rub'),
        ];
        $lastColumn = range('A', 'Z')[count($thData) - 1];

        $users = User::all();
        if (count($users) > 0) {
            $tdData = [];
            foreach ($users as $user) {
                $tdData[] = [
                    $user->first_name,
                    $user->last_name,
                    $user->email,
                    $user->phone,
                    $user->getTotalRevenue(),
                ];
            }

            CommonHelper::downloadInExel($fileName, $thData, $tdData, $lastColumn);
        }

        return redirect()->back();
    }

    /**
     * @param $userId
     * @return $this|\Illuminate\Http\RedirectResponse
     */
    public function confirmWithdrawMoney($userId)
    {
        $user = User::find($userId);
        if (is_null($user))
            return redirect()->back()
                ->withErrors(trans('messages.userDoesNotExistError', ['id' => $userId]));

        if (!$user->canWithdrawMoney())
            return redirect()->back()
                ->withErrors(trans('messages.notAuthorized'));

        $user->transactions()->create(['amount' => $user->getAvailableTransactionAmount()]);
        flash(trans('messages.success'))->success();

        return redirect()->back();
    }
}

resources/views/admin/user/edit.blade.php
@extends('layouts.admin_template')

{{--Page settings--}}
@section('title')
    {{ trans('basic.userEdit') }}
@endsection
@section('additional_styles')
    <link href="{{ mix('css/grid.css') }}" rel="stylesheet">
@endsection

{{--Activate menu item--}}
@section('userIndex') active @endsection

{{--Main page content--}}
@section('content')
    <section class="panel">
        <header class="panel-heading">
            {{ trans('basic.userEdit') }} {{ $user->email }}
        </header>
        <div class="panel-body">
            <div class="adv-table">
                <div class="space15"></div>

                <div class="panel-body">
                    {!! Form::model($user, ['route' => ['users.update', $user->id]]) !!}
                        {{ method_field('PUT') }}
                        <div class="row">
                            <div class="col-sm-6 col-xs-12">
                                <div class="form-group">
                                    {!! Form::label('first_name', trans('basic.firstName')) !!}
                                    {!! Form::text('first_name', null, ['class' => 'form-control']) !!}
                                </div>
                            </div>
                            <div class="col-sm-6 col-xs-12">
                                <div class="form-group">
                                    {!! Form::label('last_name', trans('basic.lastName')) !!}
                                    {!! Form::text('last_name', null, ['class' => 'form-control']) !!}
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-sm-6 col-xs-12">
                                <div class="form-group">
                                    {!! Form::label('email', trans('basic.email')) !!}
                                    {!! Form::email('email', null, ['class' => 'form-control']) !!}
                                </div>
                            </div>
                            <div class="col-sm-3 col-xs-12">
                                <div class="form-group">
                                    <div>
                                        {!! Form::label('social', trans('basic.userSocial'), ['class' => 'clearfix']) !!}
                                    </div>
                                    <label class="label_check">
                                        {!! Form::checkbox('social') !!}
                                    </label>
                                </div>
                            </div>
                            <div class="col-sm-3 col-xs-12">
                                <div class="form-group">
                                    <div>
                                        {!! Form::label('active', trans('basic.userActive'), ['class' => 'clearfix']) !!}
                                    </div>
                                    <label class="label_check">
                                        {!! Form::checkbox('active') !!}
                                    </label>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-xs-12">
                                <button class="btn btn-info" type="submit">
                                    {{ trans('basic.save') }}
                                </button>
                            </div>
                        </div>
                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </section>
@endsection
@section('additional_scripts')
    <script type="text/javascript" language="javascript" src="{{ mix('js/jquery.dataTables.js') }}"></script>
    <script src="{{ mix('js/grid.js') }}"></script>
@endsection

resources/views/admin/user/index.blade.php
@extends('layouts.admin_template')

{{--Page settings--}}
@section('title')
    {{ trans('basic.usersList') }}
@endsection
@section('additional_styles')
    <link href="{{ mix('css/grid.css') }}" rel="stylesheet">
@endsection
@section('additional_scripts')
    @php $item =  trans('basic.users'); @endphp
    @include('templates._dynamic_table_trans_script')
    <script type="text/javascript" language="javascript"  src="{{ mix('js/jquery.dataTables.js') }}"></script>
    <script src="{{ mix('js/grid.js') }}"></script>
@endsection

{{--Main page content--}}
@section('content')
    <section class="panel col-md-3">
        <header class="panel-heading">
            {{ trans('basic.filter') }}
        </header>
        <div class="panel-body">
            <form method="post" action="{{ route('users.filter') }}">
                {{ csrf_field() }}
                <div class="form-group">
                    <label>{{ trans('basic.firstName') }}</label>
                    <input type="text" class="form-control" value="{{ $filter['name'] or old('name') }}" name="name">
                </div>
                <div class="form-group">
                    <label>{{ trans('basic.userAge') }}</label>
                    <div class="row">
                        <div class="col-xs-6">
                            <input type="number" class="form-control" placeholder="{{ trans('basic.from')}}"
                                   value="{{ $filter['age_from'] or old('age_from') }}" name="age_from" min="0" max="150">
                        </div>
                        <div class="col-xs-6">
                            <input type="number" class="form-control" placeholder="{{ trans('basic.to')}}"  min="0" max="150"
                                   value="{{ $filter['age_to'] or old('age_to') }}" name="age_to">
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    <label>{{ trans('basic.userProducts') }}</label>
                    <div class="row">
                        <div class="col-xs-6">
                            <input type="number" class="form-control" placeholder="{{ trans('basic.from')}}" min="0"
                                   value="{{ $filter['products_from'] or old('products_from') }}" name="products_from">
                        </div>
                        <div class="col-xs-6">
                            <input type="number" class="form-control" placeholder="{{ trans('basic.to')}}" min="0"
                                   value="{{ $filter['products_to'] or old('products_to') }}" name="products_to">
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    <label>{{ trans('basic.countsDonate') }}</label>
                    <div class="row">
                        <div class="col-xs-6">
                            <input type="number" class="form-control" placeholder="{{ trans('basic.from')}}" min="0"
                                   value="{{ $filter['donate_from'] or old('donate_from') }}" name="donate_from">
                        </div>
                        <div class="col-xs-6">
                            <input type="number" class="form-control" placeholder="{{ trans('basic.to')}}" min="0"
                                   value="{{ $filter['donate_to'] or old('donate_to') }}" name="donate_to">
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    <label>{{ trans('basic.sum') }}</label>
                    <div class="row">
                        <div class="col-xs-6">
                            <input type="number" class="form-control" placeholder="{{ trans('basic.from')}}" min="0"
                                   value="{{ $filter['sum_from'] or old('sum_from') }}" name="sum_from">
                        </div>
                        <div class="col-xs-6">
                            <input type="number" class="form-control" placeholder="{{ trans('basic.to')}}" min="0"
                                   value="{{ $filter['sum_to'] or old('sum_to') }}" name="sum_to">
                        </div>
                    </div>
                </div>
                <button class="btn btn-primary" type="submit">
                    {{ trans('basic.filterBtn') }}
                </button>
            </form>
        </div>
    </section>
    <div class="col-md-9">
        <section class="panel">
            <header class="panel-heading text-right">
                <span class="pull-left">
                {{ trans('basic.usersList') }}
            </span>
                <a href="{{ route('users.download') }}" type="button" id="loading-btn" class="btn btn-warning btn-xs">
                    <i class="fa fa-download"></i> {{ trans('basic.btnDownloadData') }}
                </a>
            </header>
            <div class="panel-body">
                <div class="adv-table">
                    <div class="table-responsive">
                        <table class="table-striped table-hover display table table-bordered" id="users-table">
                            <thead>
                            <tr>
                                <th>#</th>
                                <th>{{ trans('basic.firstName') }}</th>
                                <th>{{ trans('basic.userAge') }}</th>
                                <th>{{ trans('auth.email') }}</th>
                                <th>{{ trans('basic.userProducts') }}</th>
                                <th>{{ trans('basic.countsDonate') }}</th>
                                <th>{{ trans('basic.sum') }}</th>
                                <th class="text-center">{{ trans('basic.actions') }}</th>
                            </tr>
                            </thead>
                            <tbody>
                            @php $revenue = 0; $transaction = 0; @endphp
                            @foreach($users as $model)
                                @if ($model->isUser())
                                    @php
                                        $revenue += $model->getTotalRevenue();
                                         $transaction += $model->getTransactionsAmount();
                                    @endphp
                                    <tr>
                                        <td>{{ $model->id }}</td>
                                        <td>
                                            <a href="{{ route('users.show', ['id' => $model->id]) }}" title="{{ trans('basic.view') }}">
                                                {{ $model->first_name . ' ' . $model->last_name }}
                                            </a>
                                        </td>
                                        @php $age = $model->getAge(); @endphp
                                        <td>@if ($age == 0) &mdash; @else {{ $age }} @endif</td>
                                        <td>{{ $model->email }}</td>
                                        <td>{{ $model->countProducts }}</td>
                                        <td>{{ $model->countDonateProducts }}</td>
                                        <td class="action-td-lg">
                                            {{ trans('basic.total') . ': ' }}
                                            <strong>{{ $model->getTotalRevenue() }}</strong>
                                            {{ ' ' . trans('basic.rub') }}
                                            <br>
                                            {{ trans('basic.transferred') . ': ' }}
                                            <strong>{{ $model->getTransactionsAmount() }}</strong>
                                            {{ ' ' . trans('basic.rub') }}
                                        </td>
                                        <td class="action-td-lg">
                                            {{--View items btn block--}}
                                            <a href="{{ route('users.products.index', [$model->id]) }}"
                                               class="btn btn-warning btn-xs" title="{{ trans('basic.viewProducts')}}">
                                                <i class="fa fa-shopping-cart"></i>
                                            </a>
                                            {{--Money is given in cash btn block--}}
                                            @if ($model->canWithdrawMoney())
                                                <a href="{{ route('users.confirmWithdrawMoney', [$model->id]) }}"
                                                   class="btn btn-info btn-xs" title="{{ trans('basic.moneyInCash')}}">
                                                    <i class="fa fa-money"></i>
                                                </a>
                                            @endif
                                            {{--View deliveries btn block--}}
                                            <a href="{{ route('users.deliveries.index', [$model->id]) }}"
                                               class="btn btn-success btn-xs" title="{{ trans('basic.viewExports')}}">
                                                <i class="fa fa-truck"></i>
                                            </a>
                                            {{--Delete btn block--}}
                                            <a id="del-{{ $model->id }}" href="#confirm{{ $model->id }}" class="btn btn-danger btn-xs"
                                               title="{{ trans('basic.delete')}}" data-toggle="modal">
                                                <i class="fa fa-trash-o "></i>
                                            </a>
                                            @php $delMsg = trans('messages.deleteUserConfirm',['id' => htmlspecialchars($model->id)]); @endphp
                                            @include('templates._confirm_single_deletion')
                                            <form id="delete_{{ $model->id }}" method="post" class="hidden"
                                                  action="{{ route('users.destroy', [$model->id]) }}">
                                                {{ csrf_field() }}
                                                {{ method_field('DELETE') }}
                                            </form>
                                        </td>
                                    </tr>
                                @endif
                            @endforeach
                            </tbody>
                        </table>
                    </div>
                    {{ trans('basic.toTransfer', ['sum' => htmlspecialchars($revenue - $transaction)]) }}
                </div>
            </div>
        </section>
    </div>
@endsection

resources/views/admin/user/show.blade.php
@extends('layouts.admin_template')

@section('title')
    {{ $user->first_name . ' ' . $user->last_name }}
@endsection

@section('content')
    @widget('Profile', ['user' => $user, 'admin' => true])
@endsection